---
- name: remove yum.pid
  file: 
    path: "/var/run/yum.pid"
    state: "absent"

- name: delete repo dir
  file:
    path: "/etc/yum.repos.d"
    state: "absent"

- name: create repo dir
  file:
    path: "/etc/yum.repos.d"
    state: "directory"

- name: Add yum repository
  template:
    src: repos/{{ item }}
    dest: /etc/yum.repos.d/{{ item }}
    mode: 0644
  with_items:
    - centos-7.repo
    - epel-7.repo
    - ceph.repo

- name: yum clean all
  command: yum clean all

- name: yum makecache
  command: yum makecache

- name: configure yum tools
  package:
    name: "yum-utils"
    state: "present"

- name: install epel-release
  yum:
    name: "epel-release"
    state: "present"
    disable_gpg_check: "yes"

- name: rpm add key RPM-GPG-KEY-EPEL-7
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
